Task_1/Task_Mvc/Models/VMEmployee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Task_Mvc.Models
{
    public class VMEmployee
    {
        public int EMP_ID { get; set; }
        public string EMP_NAME { get; set; }
        public int EMP_AGE { get; set; }
        public string EMP_CITY { get; set; }
    }
}

Task_1/Task_Mvc/Controllers/DemoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task_Mvc.Controllers
{
    public class DemoController : Controller
    {
        // GET: Demo
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task_1/Task_Mvc/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using Task_Mvc.Repository;
using Task_Mvc.Models;
using Newtonsoft.Json;

namespace Task_Mvc.Controllers
{
    public class EmployeeController : Controller
    {

        EmployeeRepository employeeRepository = new EmployeeRepository();

        // GET: Employee
        public ActionResult Index()
        {
            return View();
        }

        public async Task<JsonResult> SaveEmployee(VMEmployee vMEmployee)
        {
            string response = string.Empty;
            try
            {
                response = await employeeRepository.SaveEmployee(vMEmployee);
            }
            catch (Exception ex)
            {
                response = "-99" + " Error :" + ex.Message;
            }
            return Json(response);
        }


        public async Task<JsonResult> GetEmployeeList(VMEmployee vmEmployee)
        {
            List<VMEmployee> list = new List<VMEmployee>();
            try
            {
                string response = await employeeRepository.GetEmployeeList(vmEmployee);
                if (response != null && response != "")
                    list = JsonConvert.DeserializeObject<List<VMEmployee>>(response);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
            return Json(list, JsonRequestBehavior.AllowGet);
        }



        public async Task<JsonResult> GetEmployeeById(int id)
        {
            VMEmployee vmEmployee = new VMEmployee();
            try
            {
                string response = await employeeRepository.GetEmployeeById(id);
                if (response != null && response != "")
                    vmEmployee = JsonConvert.DeserializeObject<VMEmployee>(response);
            }
            catch (Exception ex)
            {
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
            return Json(vmEmployee, JsonRequestBehavior.AllowGet);
        }


    }
}

Task_1/Task_Mvc/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task_Mvc.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Task_1/Task_Mvc/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Task_Mvc.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index()
        {
            return View();
        }
    }
}

Task_1/Task_Mvc/Views/Employee/Index.cshtml
@{
    ViewBag.Title = "Index";
}




<html>
<head>
    <title>Employee</title>
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-icons-1.11.3/font/bootstrap-icons.min.css" rel="stylesheet" defer />
    <link href="~/Content/iziToast-master/dist/css/iziToast.min.css" rel="stylesheet" defer />
</head>
<body>
    <div align="center">
        <h1><b>Employee Task</b></h1>
        <br />

        <label>Emp Name</label>
        <input type="text" id="txtEmpName" placeholder="Jon" />
        <br />
        <br />

        <label>Emp Age   :-</label>
        <input type="number" id="txtEmpAge" placeholder="20" />
        <br />
        <br />

        <label>Emp City   :-</label>
        <input type="text" id="txtEmpCity" placeholder="Pune" />
        <br />
        <br />

        <button class="btn btn-primary" id="btnSaveEmp"> Save Employee</button>
        <button class="btn btn-danger" id="btnClear"> Clear</button>
        <input type="hidden" id="hdnEmpId" value="" />
    </div>

    <br />
    <br />

    <table class="table table-striped">
        <thead>
            <tr>
                <th class="text-primary">Employee Id</th>
                <th class="text-primary">Employee Name</th>
                <th class="text-primary">Employeemp Age</th>
                <th class="text-primary">Employee City</th>
                <th class="text-primary">Action</th>
            </tr>
        </thead>
        <tbody id="tblEmployee">
        </tbody>
    </table>


    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Content/iziToast-master/dist/js/iziToast.min.js"></script>

    <script src="~/Scripts/Master/Employee.js"></script>

</body>
</html>

Task_1/Task_Mvc/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Task_1/Task_Mvc/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Task_1/Task_Mvc/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Task_1/Task_Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                @Html.ActionLink("Basic POC", "Index", "Employee", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Add Employee", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Employee List", "Index", "Employee")</li>
                    <li>@Html.ActionLink("Employee", "Index", "Employee")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Task_1/Task_Mvc/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Student</h2>

<html>
<head>
    <title>Student</title>
</head>
<body>

    <h1>Student</h1>

    <div class="col-md-8 col-sm-12 mt--1 col-xs-12">
        <div class="form-group attached_Doc" style="">
            <div class="table-responsive">
                <table id="tblAssociationDoc">
                    <tbody>
                        <tr id="addDocRow">
                            <td class="col-sm-3" id="tourEnterAttachmentName">
                                <label>COURSENAME</label>
                                <input type="text" class="form-control txtAttachmentName" id="txtAttachmentName" tabindex="1" name="txtAttachmentName" value="" >
                            </td>
                            <td class="col-sm-3" id="tourUpload">
                                <label>SHORTNAME</label>
                                <input type="text" class="form-control fileAttachmentUpload" id="fileAttachmentUpload" tabindex="1" name="fileAttachmentUpload" value="" >
                            </td>
                            <td class="col-sm-3" id="tourUpload">
                                <label>CODE</label>
                                <input type="text" class="form-control fileAttachmentUpload" id="fileAttachmentUpload" tabindex="1" name="fileAttachmentUpload" value="" >
                            </td>
                            <td class="col-sm-3" id="tourUpload">
                                <label>CREDITS</label>
                                <input type="text" class="form-control fileAttachmentUpload" id="fileAttachmentUpload" tabindex="1" name="fileAttachmentUpload" value="" >
                            </td>
                            <td class="col-sm-3" id="tourUpload">
                                <label>COURSE_TYPE_ID</label>
                                <input type="text" class="form-control fileAttachmentUpload" id="fileAttachmentUpload" tabindex="1" name="fileAttachmentUpload" value="" >
                            </td>
                            <td class="col-sm-2 text-center" id="tourAddButton">
                                <br>
                                <button id="addDoc" class="btn btn-primary">Add <i class="fa fa-plus"></i></button>
                                <input type="hidden" id="txtAlumniId" name="txtAlumniId" value="">
                            </td>
                        </tr>
                    </tbody>
                    <tbody id="newRowAdd" algin="center"></tbody>
                </table>
            </div>
        </div>
    </div>



    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/Master/Demo.js"></script>

</body>
</html>